# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 21:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.TextField(choices=[('Rockingham', 'Rockingham'), ('Other', 'Other'), ('Guilford', 'Guilford'), ('Forsyth', 'Forsyth'), ('Montgomery', 'Montgomery'), ('Randolph', 'Randolph'), ('Alamance', 'Alamance')])),
                ('school_name', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ja_social.UserProfile')),
            ],
        ),
    ]
