# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ja_social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrecord',
            name='hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteerrecord',
            name='ja_program',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='volunteerrecord',
            name='county',
            field=models.TextField(choices=[('Other', 'Other'), ('Alamance', 'Alamance'), ('Montgomery', 'Montgomery'), ('Rockingham', 'Rockingham'), ('Forsyth', 'Forsyth'), ('Randolph', 'Randolph'), ('Guilford', 'Guilford')]),
        ),
    ]
