# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ja_social', '0002_auto_20161022_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerrecord',
            old_name='user',
            new_name='user_prof',
        ),
        migrations.AlterField(
            model_name='volunteerrecord',
            name='county',
            field=models.CharField(choices=[('Alamance', 'Alamance'), ('Forsyth', 'Forsyth'), ('Guilford', 'Guilford'), ('Montgomery', 'Montgomery'), ('Randolph', 'Randolph'), ('Rockingham', 'Rockingham'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='volunteerrecord',
            name='ja_program',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='volunteerrecord',
            name='school_name',
            field=models.CharField(max_length=30),
        ),
    ]
