# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ja_social', '0003_auto_20161022_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerrecord',
            old_name='user_prof',
            new_name='user_profile',
        ),
    ]
