# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ja_social', '0004_auto_20161022_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrecord',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
