# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ja_social', '0005_auto_20161022_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerrecord',
            old_name='ja_program',
            new_name='JA_program',
        ),
    ]
