# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ja_social', '0007_auto_20161023_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.URLField(default='volunteer.jpg'),
        ),
    ]
