# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ja_social', '0008_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.CharField(default='volunteer.jpg', max_length=128),
        ),
    ]
