# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ja_social', '0009_auto_20161023_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default=None, null=True, upload_to='uploads/profile_pics/'),
        ),
    ]
