# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ja_social', '0011_auto_20161023_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerrecord',
            name='JA_program',
            field=models.CharField(choices=[('JA Ourselves', 'JA Ourselves'), ('JA Our Families', 'JA Our Families'), ('JA Our Community', 'JA Our Community'), ('JA Our City', 'JA Our City'), ('JA Our Region', 'JA Our Region'), ('JA Our Nation', 'JA Our Nation'), ('JA Economics for Success', 'JA Economics for Success'), ('JA Global Marketplace - Kit Based', 'JA Global Marketplace - Kit Based'), ('JA Global Marketplace - Blended Model', 'JA Global Marketplace - Blended Model'), ("JA It's My Future", "JA It's My Future"), ('JA Be Entrepreneurial', 'JA Be Entrepreneurial'), ('JA Career', 'JA Career'), ('JA Company Program - Blended Model', 'JA Company Program - Blended Model'), ('JA Economics', 'JA Economics'), ('JA Exploring Economics', 'JA Exploring Economics'), ('JA Job Shadow', 'JA Job Shadow'), ('JA Personal Financial', 'JA Personal Financial'), ('JA Personal Financial - Blended Model', 'JA Personal Financial - Blended Model'), ('JA Titan', 'JA Titan')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteerrecord',
            name='county',
            field=models.CharField(choices=[('Alamance', 'Alamance'), ('Forsyth', 'Forsyth'), ('Guilford', 'Guilford'), ('Montgomery', 'Montgomery'), ('Randolph', 'Randolph'), ('Rockingham', 'Rockingham'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteerrecord',
            name='school_name',
            field=models.CharField(max_length=50),
        ),
    ]
