# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 10:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ja_social', '0012_auto_20161023_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='uploads/profile_pics/')),
                ('date_uploaded', models.DateField(default=datetime.date.today)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ja_social.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='volunteerrecord',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
