# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ja_social', '0013_auto_20161023_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photorecord',
            old_name='uploader',
            new_name='user_profile',
        ),
        migrations.AlterField(
            model_name='photorecord',
            name='photo',
            field=models.ImageField(upload_to='uploads/gallery_pictures/'),
        ),
    ]
