# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ja_social', '0014_auto_20161023_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
